fspiritosi/gym-go

api/.gitignore
api/package-lock.json
api/package.json
api/src/index.js

Se agregaron dependencias al package.json y se denero el index.js
Pendiente para proximo PR servidor con express

dependencias agregadas

---

api/index.js
api/src/app.js
api/src/index.js

iniciando el servidor

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/components/txt
client/src/index.js
client/src/redux/reducer.js
client/src/redux/store.js
client/tailwind.config.js

Se realizo la instalacion de las dependencias a utilizar asi como el Redux, 
Se eliminaron las carpetas anteriores de components, para trabajarlas diferentes ramas.

Instalacion de Dependencias, Redux y Limpiando Carpetas en Components

---

client/src/App.js

se agrega import de Axios y axios.dedfault.baseURL en app.js

Creando el axios.default.baseURL en App.js

---

client/src/views/Detail/Detail.jsx

Componente detail

---

client/src/components/Nav/Nav.jsx
client/src/components/Nav/Navbar.css

componenteNav

---

client/src/components/Nav/Nav.jsx

arreglado el useState

---

client/src/components/Activities/Activities.jsx
client/src/components/CardActivities/CardActivities.jsx

Mas cambios al componente 
Revison de renderizado de Goals y link en el boton detail

update render goals y link button detail component

---

client/src/components/CardActivities/CardActivities.jsx

Se actualiza nuevamente componente activities

Activities new component

---

client/src/components/Activities/Activities.jsx
client/src/components/FilterandSort/FilterandSort.jsx
client/src/redux/actions.js
client/src/redux/reducer.js

Se crea componente de filtro y ordenamiento
Se importa en componente activities

filter and sort activities

---

client/src/components/Nav/Nav.jsx
client/src/components/Nav/Navbar.css
client/src/views/Detail/Detail.jsx
client/src/views/FormCreateActivities/FormCreateActivities.jsx
client/src/views/FormCreateActivities/FormCreateActivities.module.css

- en el Navbar se modifico el link de activities para que nos redireccione a '/activities'
- se crearon estilos del navbar
- se crearon estilos del formulario

agregando estilos

---

client/src/components/FilterandSort/FilterandSort.jsx
client/src/components/FilterandSort/FilterandSort.module.css
client/src/components/SearchBar/SearchBar.jsx
client/src/components/SearchBar/SearchBar.module.css
client/src/views/Activities/Activities.jsx

-Se agregan estilos a filtros y search bar

update styles filters y searchbar

---

client/src/views/FormCreateActivities/FormCreateActivities.jsx

Se reparo bug de carga de imagenes en el form

reparando bug de carga de imagenes

---

client/src/App.js
client/src/components/Footer/Footer.jsx
client/src/components/Footer/footer.css

falta todas las imagenes pero eso tenemos que ver entre todos o sube cada uno a la carpeta correspondiente asi despues hago bien las rutas y los links

componente footer primera version

---

client/package-lock.json
client/package.json
client/src/components/Activities/Activities.jsx
client/src/components/CardActivities/CardActivities.jsx
client/src/components/CardActivities/CardActivities.module.css

Faltan mas modificaciones, pero para poder ir viendo como queda

cambio 1 vista activities

---

client/.env
client/package-lock.json
client/package.json
client/setupTests.js
client/src/App.js
client/src/components/Login/LoginButton.js
client/src/components/Login/LogoutButton.js
client/src/components/Login/Profile.js
client/src/components/Nav/Nav.jsx
client/src/index.js
client/src/views/Landing/Landing.jsx

Login funcionando no conectado a DB

Login auth0

---

client/src/App.js
client/src/components/CardProfesores/CardProfesores.jsx
client/src/components/CardProfesores/CardProfesores.module.css
client/src/redux/actions.js
client/src/redux/reducer.js
client/src/views/Profesores/Profesores.jsx
client/src/views/Profesores/ejemploprofesores.json

Se hizo vista profesores donde muestra nombre imagen y descripcion del coache 
Se trabajo con un json provisional y de agrego la ruta en App.js
-Pendiente estilos con taiwind
se uso css puro

View profesores front segunda version

---

api/src/controllers/activitiesControllers.js
api/src/controllers/classesController.js
api/src/controllers/eventController.js
api/src/handlers/classesHandler.js
api/src/models/Classes.js
api/src/models/Events.js
client/src/App.js
client/src/components/Activities/Activities.jsx
client/src/components/FormCreateActivities/CludinatyUploadComponent.jsx
client/src/components/FormCreateActivities/FormCreateActivities.jsx
client/src/components/FormCreateActivities/FormCreateActivities.module.css

Se medifico la creación de eventos.
Se agregegó el id de Clases en cada evento para poder tomarlo desde el front.
Se agregó información a lo que devuelve el modelo activities

Fix bugs01

---

api/src/controllers/activitiesControllers.js
api/src/controllers/classesController.js
api/src/controllers/coachesController.js
api/src/handlers/classesHandler.js
api/src/handlers/coachesHandler.js
api/src/routes/coachesRouter.js
api/src/routes/index.js
client/src/App.js
client/src/views/FormCreateActivities/FormCreateActivities.jsx

Se crea la ruta de profesores solo los metodos GET y POST
se modifica el controller de Activities para que cargue el id del profesor.
Se modifica el controller de Classes porque el coachId se encontraba comentado en la creación.

Ruta coaches

---

client/src/components/CardProfesores/CardProfesores.jsx
client/src/components/CardProfesores/CardProfesores.module.css
client/src/components/Login/Login.module.css
client/src/components/Login/LoginButton.js
client/src/components/Login/LogoutButton.js
client/src/views/Profesores/Profesores.jsx
client/src/views/Profesores/ejemploprofesores.json

-Se agrego la ruta coaches de api al componente profesores,  se crearon las actions y reducers necesarios
-Se cambio el estilo de la view
-Se le dio estilo al boton log in y log out

Update view profesores rute coaches

---

client/src/components/Activities/Activities.jsx
client/src/components/Activities/Activities.module.css
client/src/components/CardActivities/CardActivities.jsx
client/src/components/FilterandSort/FilterandSort.jsx
client/src/redux/actions.js
client/src/redux/reducer.js
client/src/views/Landing/Landing.jsx
client/src/views/Landing/Landing.module.css

-Se dio estilos al componente activities y al landing(solo texto)
-Se modifico el filtro de goals
Filtro por goals ok
Por dificultad pendiente

updates activities, cardactivities, actions reducer firlter goals

---

api/src/models/User.js

sacando bcrypt

---

api/src/models/User.js

sacando el allowNull del username

username not allowNull

---

api/src/models/User.js
api/src/models/Usuario.js

Deploy prueba auth0

---

client/package-lock.json
client/package.json
client/src/components/CardPaqueteClase/CardPaquete.module.css
client/src/components/CardPaqueteClase/CardPaqueteClase.jsx
client/src/components/Footer/Footer.jsx
client/src/views/PaquetesClases/PaquetesClases.jsx

-Se instalo react-modal en  las dependencias
-Se realizo la logica para que aparezca el modal en caso de que el usuario no este logueado, 
aparece un texto y 3 botones, iniciar sesion , registrarse (Dirigen a Auth0) o cerrar.(se aplico un minimo de estilos solo para que no se vea desenfocado)
-Comente lo que hay en Footer.jsx ya que me estaba causando conflicto desde ayer (lo revise con Juan)
-No toque navbar,  los botones que estan en componente login no se ven renderiados (estan comentados dentro de navbar)

prueba modal vista comprar paquetes

---

client/src/components/Footer/Footer.jsx

Styles tailwind

---

api/package-lock.json
api/package.json
api/src/controllers/userController.js
api/src/handlers/userHandler.js
api/src/routes/userRouter.js
api/src/utils/jwt.js
api/src/utils/nodemailer.js

1- Instalar nodemailer en api
2- Se modificaron dos rutas para mejor identificacion del edpoint      
userRouter.post("/users/register", userRegister); se agrego /users/register/ 
userRouter.post("/users/login", userLogin); se agrego /users/login
2-esta pendiente elaborar el ajustar el middleware para la ruta adquisision de paquetes que le llegue la notoficacion

notificaciones

---

client/src/components/CardClasses/CardClasses.jsx
client/src/components/CardClasses/CardClasses.module.css
client/src/views/Classes/Classes.jsx

-Se volvio a actualizar el componente clases 
-Se manejo  notificacion toastify se momento al dar clic en boton de reserva de evento 
-Se agrego la logica de isactive de clases
-Pendiente dar logica a botones con las fechas disponibles y deshabilitar en caso contrario

Componente clases logica y modal update

---

client/src/components/CardClasses/CardClasses.jsx
client/src/components/CardClasses/CardClasses.module.css
client/src/redux/actions.js
client/src/redux/reducer.js
client/src/views/Classes/Classes.jsx

-Se avanzo en la logica para reservar evento con el id de usuario por medio el put
trabaje en las actions, reducer y los componentes classes y cardclasses
creo que esta pendiente que en users se muestren los eventos al que se suscriben los usuarios
visualmente se aprecia asi el componente 
cuando se suscriben actualiza los cupos disponibles a ese evento 
-Pendiente de optimizar
*estilos
*los botones don las fechas de los eventos se van cambiando pero la suscripcion si la hace correctamente 
*falta que deshabilite el boton cuando el cupo esta lleno de momento solo manda la nortificacion tanto registro como de cupo lleno
*Revisar por que no sale la notificacion de que ya esta suscrito a evento si quiere volver a suscribirse 
Hasta aqui mi reporte

Componente clases a partir de rama develop actualizada

---

client/src/App.js
client/src/auth0-provider-with-navigate.js
client/src/components/Login/LoginButton.js
client/src/components/Login/LogoutButton.js
client/src/components/Protected-route/authentication-guard.js

Agregado el componente protector de rutas y login dirigido a activities

Develop rutas protegidas

---

client/src/components/CardClasses/CardClasses.jsx
client/src/components/CardClasses/CardClasses.module.css
client/src/views/Classes/Classes.jsx

-Se  agregaron notificaciones en caso de no tener creditos o si ya esta inscrito, al igual que el manejo de error, 
actualiza user, events y clases  en las  condicionales del handlereserva (creo que exagere con el uso del dispatch)
*******Pendiente  :(
La data events se sigue moviendo despues del put en el evento , ya intente ordenarlas con sort despues del put pero sigue igual 
lo que hice de momento fue que una vez inscrito aparezca la palabra suscrito arriba del evento al que aplico 
Faltan algunas validaciones para el disable del boton cuando el cupo esta lleno
Logueo real con los datos del usuario, actualmente se usa el id de algun usuario de los creados en la base de datos para hacer el ejemplo .

Updates componente classes

---

client/src/components/Login/Profile.js

reparando el profile

---

api/src/controllers/classesController.js
client/src/App.js
client/src/components/Login/Profile.js

Se agregaron en el classController los atributos 
- 'image' del modelo Activities
- 'profilePicture' del modelo Coaches

Fix01 classes controller

---

api/src/controllers/eventController.js
api/src/controllers/ordersController.js
api/src/controllers/userController.js
client/src/App.js
client/src/components/CardCompras/CardCompras.jsx
client/src/components/CardPaqueteClase/CardPaqueteClase.jsx
client/src/components/CardReservas/CardReservas.jsx
client/src/components/Login/Profile.js
client/src/views/Landing/Landing.jsx
client/src/views/UserProfile/UserProfile.jsx

Se creó nuevo archivo en carpeta views UserProfile.jsx. Se trae la data del usuario logedo de redux y renderiza:
1) créditos disponibles
2) botón para comprar mas con link a /prices
3) card container con cards de sus reservas > cada card de reserva es un componente nuevo CardReservas.jsx
4) card container con las cards de las compras que hizo > cada card de compra es un componente nuevo CardCompras.jsx

view UserProfile + componentes CardCompras y CardReservas

---

api/src/app.js
client/src/components/CardCompras/CardCompras.jsx
client/src/components/CardReservas/CardReservas.jsx
client/src/views/PaquetesClases/PaquetesClases.jsx
client/src/views/Profesores/Profesores.jsx
client/src/views/UserProfile/UserProfile.jsx
client/tailwind.config.js

estilos en profile

---

api/src/app.js
api/src/controllers/ordersController.js
client/src/App.js
client/src/views/Admin/adminComponentes/Cards.jsx
client/src/views/Admin/adminComponentes/SalesCard.jsx
client/src/views/Admin/scenes/Dashboard/Dashboard.jsx
client/src/views/Admin/scenes/Tables/CoachesData.jsx
client/src/views/Admin/scenes/Tables/SalesData.jsx
client/src/views/Admin/scenes/Users/Users.jsx
client/src/views/Admin/scenes/global/Sidebar.jsx

Se agregaron las tablas de usuarios y ventas
Se crearon tarjetas en vista Dashboard

Mejora dashboard 01

---

api/src/app.js
client/src/App.js
client/src/components/CardClasses/CardClasses.jsx
client/src/components/CardCompras/CardCompras.jsx
client/src/components/CardPaqueteClase/CardPaqueteClase.jsx
client/src/components/CardReservas/CardReservas.jsx
client/src/components/Modal/Modal.js
client/src/components/Nav/Nav.jsx
client/src/components/sidebarcoaches/searchbarclasses.jsx
client/src/components/sidebarcoaches/sidebar2.jsx
client/src/views/Classes/Classes.jsx
client/src/views/Detail/Detail.jsx
client/src/views/PaquetesClases/PaquetesClases.jsx
client/src/views/PaquetesClases/ejemplopaquetesclases.json
client/src/views/UserProfile/UserProfile.jsx

cambios de estilos
